// Initialisation de l'application
document.addEventListener('DOMContentLoaded', async () => {
    await db.init();
        
            // Charger les statistiques
                loadStatistics();
                    
                        // Animation de défilement fluide
                            setupSmoothScrolling();
                                
                                    // Animation des nombres
                                        animateNumbers();
                                        });

                                        async function loadStatistics() {
                                            const stats = await db.getStatistics();
                                                
                                                    // Mettre à jour les compteurs
                                                        document.getElementById('totalQuestions').textContent = stats.totalQuestions;
                                                            document.getElementById('totalModules').textContent = stats.totalModules;
                                                                document.getElementById('totalYears').textContent = stats.totalYears;
                                                                    
                                                                        // Mettre à jour les compteurs par module
                                                                            if (stats.moduleBreakdown) {
                                                                                    document.getElementById('medecineCount').textContent = 
                                                                                                `${stats.moduleBreakdown.medecine || 0} questions`;
                                                                                                        document.getElementById('chirurgieCount').textContent = 
                                                                                                                    `${stats.moduleBreakdown.chirurgie || 0} questions`;
                                                                                                                            document.getElementById('biologieCount').textContent = 
                                                                                                                                        `${stats.moduleBreakdown.biologie || 0} questions`;
                                                                                                                                            }
                                                                                                                                            }

                                                                                                                                            function setupSmoothScrolling() {
                                                                                                                                                document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                                                        anchor.addEventListener('click', function (e) {
                                                                                                                                                                    e.preventDefault();
                                                                                                                                                                                const target = document.querySelector(this.getAttribute('href'));
                                                                                                                                                                                            if (target) {
                                                                                                                                                                                                            target.scrollIntoView({
                                                                                                                                                                                                                                behavior: 'smooth',
                                                                                                                                                                                                                                                    block: 'start'
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            function animateNumbers() {
                                                                                                                                                                                                                                                                                                const observerOptions = {
                                                                                                                                                                                                                                                                                                        threshold: 0.5,
                                                                                                                                                                                                                                                                                                                rootMargin: '0px'
                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            const observer = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                    entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                                if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                const target = entry.target;
                                                                                                                                                                                                                                                                                                                                                                                const finalValue = parseInt(target.textContent);
                                                                                                                                                                                                                                                                                                                                                                                                animateValue(target, 0, finalValue, 2000);
                                                                                                                                                                                                                                                                                                                                                                                                                observer.unobserve(target);
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                        }, observerOptions);
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll('.stat-number').forEach(stat => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        observer.observe(stat);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            function animateValue(element, start, end, duration) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const range = end - start;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const increment = range / (duration / 16);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let current = start;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const timer = setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current += increment;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (current >= end) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.textContent = end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clearInterval(timer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.textContent = Math.floor(current);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 16);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }